### ISSUE TITLE
Carlo Sherlock

### ISSUE THREAD

**Issue by robbisg** [robbisg/mvpa_itab_wu#28]

**Comment by robbisg** [comment]
# Preprocessing
- [ ] Put in a BIDS format
- [ ] Transform AFNI pipeline to work with BIDS
- [ ] Use fmriprep (optional)

# GLM

**Comment by robbisg** [comment]
# Retrieval Related Activity
Using the `retrieval` session, the main goal of this analysis is to shed light on the difference between dimensions in the retrieval activity.
The main goal is to understand whether differences between dimensions of retrieval (temporal, spatial, verbal, detail).

## GLM
Our purpose is to highlight differences in maps (topography, magnitude) related also to performances (confidence, accuracy)

### Analyses
- [ ] `GLM-0`: TITLE + SENT + SEA*ACC + RESP
- [ ] `GLM-1`: TITLE + SENT + SEA*DIM*ACC + RESP
- [ ] `GLM-2`: TITLE + SENT + SEA*DIM*ACC*CONF + RESP

## RSA
Representational Similarity Analysis to understand pattern differences between dimensions and scenes. 
We can use ROI from `GLM-0`, an atlas or searchlight.
The pattern can be  

### Analyses
- [ ] `RSA-1`: Pattern (average) of SEA similarity, check scene matrix and dimension matrix.
- [ ] `RSA-2`: Pattern (PCA) of SEA similarity

**Comment by robbisg** [comment]
# Replay
Replay is the capacity of replaying patterns of activity similar to those elicited by _encoding_ during _resting state_.
We wanted to investigate scene-specific replay.
We can use the algorithm used in Guidotti et al. 2015

Questions:
- [ ] Rest pre task vs rest post task
- [ ] Rest pre task vs rest post run
- [ ] Replay vs Reinstatement
- [ ] Replay is related to future reinstatement

**Comment by robbisg** [comment]
![WhatsApp Image 2021-10-05 at 15 53 52](https://user-images.githubusercontent.com/695037/136176288-4e52cf8b-16a4-4cad-b16c-320ac718929a.jpeg)

**Comment by robbisg** [comment]
## Resources

http://moments.csail.mit.edu/

https://pyscenedetect.readthedocs.io/en/latest/

**Comment by robbisg** [comment]
## Problems
After performing the GLM and looking at L vs R betas, we found no specific patterns for movement in L vs R in motor cortex.
We checked with previous analyses whether something was wrong.

:x: In session _retrieval_ and subject _matsim_ the images of run 2 and 9 were copied wrongly: so run 2 is equal to run 11, while 9 is equal to 6, scripts were right but images were copied wrongly.

**Comment by robbisg** [comment]
## Previous analyses
### GLM_NoType
Modeled variables: Title (6), Sentence (2), Search (6), Resp (1)

### GLM_ST
Modeled variables: Title (6), Sentence (2), Search_[1-24] (6), Resp_[L,R,NR] (1)

### GLM_Type
Modeled variables: Title (6), Sentence (2), Search_[Type]_[Correct] (6), Resp_[L,R,NR] (1)
For this analysis a paired contrast was performed (glt.*.nii.gz)

**Comment by robbisg** [comment]
## TODO
- [ ] Crea da python lo script preprocessing 
- [ ] Crea da python lo script GLM

**Comment by robbisg** [comment]
# Issues Federica

- [ ] `uber_subject.py` is linked to her windows system (AnyDesk problem?)
- [ ] `3dttest++` validate
- [ ] Events file with `-1` check why
- [ ] Some files have shorter number of colums
