### ISSUE TITLE
Manoscritto VAS2

### ISSUE THREAD

**Issue by robbisg** [robbisg/mvpa_itab_wu#46]
# TODO
- [x] Analisi time-wise dell'errore relativo + clusterlevel thresholding
- [x] Rifare le figure con relative error + scatterplot onset vs positioning
- [x] Utilizzare colori absolute
- [x] Figure 5 solo panel C
